#!/bin/bash
# ##################################################
# NAME:
#   hl
# DESCRIPTION:
#   Highlight specific words or terms in your text 
#   output with colors.
# AUTHOR:
#   bytebutcher
# ##################################################

# ANSI color codes
declare -A COLORS
COLORS[--red]='\033[1;31m'
COLORS[--green]='\033[1;32m'
COLORS[--blue]='\033[1;34m'
COLORS[--yellow]='\033[1;33m'
COLORS[--magenta]='\033[1;35m'
COLORS[--cyan]='\033[1;36m'
COLORS[--white]='\033[1;37m'
NO_COLOR='\033[0m'

if [[ "$#" -lt 2 || "$1" == "--help" || "$1" == "-h" ]]; then
    echo "Usage: echo \"text\" | hl --color1 term1 term2 ... --colorN termN ..."
    echo "Available colors: ${!COLORS[@]}"
    exit 0
fi

while [[ "$#" -gt 0 ]]; do
    # Get the current color and terms
    COLOR="$1"
    shift

    # Check if the color is valid
    if [[ ! "${COLORS[$COLOR]+_}" ]]; then
        echo "Invalid color: $COLOR. Use one of: ${!COLORS[@]}"
        exit 1
    fi

    while [[ "$#" -gt 0 && ! "${COLORS[$1]+_}" ]]; do
        TERM="$1"
        # Use sed to apply highlighting
        exec < <(sed -E "s/($TERM)/$(echo -e ${COLORS[$COLOR]})\1$(echo -e ${NO_COLOR})/g")
        shift
    done
done

cat
